version: '3.1'

services:

  app:
    container_name: games
    build: .
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:14.2-alpine
    container_name: pgbackend
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTPASS

    volumes:
      - database_postgres:/var/lib/postgresql/data
    
    networks:    
      - backend

volumes:
  database_postgres:

networks:
  backend: